import Image from "next/image";
import Link from "next/link";

export const metadata = { title: "Acesso administrativo | Conselho Municipal de Saude", robots: { index: false, follow: false } };

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams;
  return <main className="grid min-h-screen place-items-center bg-[#f7faf8] p-6 text-slate-900"><section className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-xl"><Link href="/" className="flex items-center gap-3"><Image src="/cms-logo.jpeg" alt="Logotipo do Conselho Municipal de Saude" width={52} height={52} className="rounded-xl" /><span><strong className="block text-sm text-emerald-950">Conselho Municipal de Saude</strong><span className="text-xs text-slate-600">Area administrativa</span></span></Link><h1 className="mt-8 text-3xl font-bold tracking-tight text-emerald-950">Acesso restrito</h1><p className="mt-3 leading-6 text-slate-600">Entre com as credenciais administrativas fornecidas pelo Conselho.</p>{error ? <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-medium text-red-800">E-mail ou senha incorretos.</p> : null}<form method="post" action="/api/admin/login" className="mt-7 grid gap-4"><label className="grid gap-2 text-sm font-bold text-slate-700">E-mail<input name="email" type="email" autoComplete="email" required className="rounded-xl border border-slate-300 px-4 py-3 font-normal outline-none focus:border-emerald-700 focus:ring-2 focus:ring-emerald-100" /></label><label className="grid gap-2 text-sm font-bold text-slate-700">Senha<input name="password" type="password" autoComplete="current-password" required className="rounded-xl border border-slate-300 px-4 py-3 font-normal outline-none focus:border-emerald-700 focus:ring-2 focus:ring-emerald-100" /></label><button className="mt-2 rounded-xl bg-emerald-800 px-5 py-3 font-bold text-white hover:bg-emerald-700">Entrar na area administrativa</button></form><Link href="/" className="mt-6 inline-flex text-sm font-semibold text-emerald-800 hover:text-emerald-600">Voltar ao portal</Link></section></main>;
}
