import Link from "next/link";
import { redirect } from "next/navigation";
import { requireAdmin } from "../../../lib/session";
import { canApproveUsers, listUsersAndRequests, roleLabel, userRoles, type UserRole } from "../../../lib/users";

export const dynamic = "force-dynamic";
export const metadata = { title: "Usuários e aprovações | CMS", robots: { index: false, follow: false } };

const statusLabel = { pendente: "Aguardando aprovação", ativo: "Ativo", suspenso: "Suspenso", rejeitado: "Rejeitado" } as const;

export default async function UsersPage({ searchParams }: { searchParams: Promise<{ salvo?: string; erro?: string }> }) {
  const session = await requireAdmin();
  if (!canApproveUsers(session)) redirect("/admin?acesso=negado");
  const [{ users, passwordRequests }, state] = await Promise.all([listUsersAndRequests(), searchParams]);
  const pending = users.filter((user) => user.status === "pendente");
  const registered = users.filter((user) => user.status !== "pendente");
  return <main className="min-h-screen bg-[#f2f7fb] text-[#40566a]">
    <header className="border-b border-[#cbdce8] bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/admin" className="font-bold text-[#17375e]">← Painel administrativo</Link><span className="text-sm font-semibold">{session.isCmsPresident ? "Presidente do CMS" : "Administrador master"}</span></div></header>
    <section className="mx-auto max-w-7xl px-6 py-12"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#28738c]">Governança de acesso</p><h1 className="mt-3 text-4xl font-bold text-[#17375e]">Usuários e aprovações</h1><p className="mt-4 max-w-3xl leading-7">Novos membros não acessam o sistema até a aprovação. Somente o master altera níveis e concede controle administrativo.</p>
      {state.salvo ? <p className="mt-6 rounded-xl border border-teal-200 bg-teal-50 p-4 font-bold text-teal-800">Alteração registrada no histórico de auditoria.</p> : null}{state.erro ? <p className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">Não foi possível concluir a operação.</p> : null}

      <h2 className="mt-10 text-2xl font-bold text-[#17375e]">Cadastros aguardando o Presidente</h2>
      <div className="mt-5 grid gap-4">{pending.length ? pending.map((user) => <article key={user.id} className="rounded-2xl border border-[#d5e3ec] bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="text-lg font-bold text-[#17375e]">{user.fullName}</h3><p className="mt-1 text-sm">{user.email}</p><p className="mt-3 text-sm"><strong>Função:</strong> {user.councilPosition ?? "Não informada"} · <strong>Segmento:</strong> {user.councilSegment ?? "Não informado"}</p><p className="mt-1 text-xs">Solicitado em {new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Cuiaba" }).format(new Date(user.createdAt))}</p></div><div className="flex items-start gap-2"><form method="post" action={`/api/admin/usuarios/${user.id}/aprovar`}><button className="rounded-xl bg-emerald-800 px-4 py-2 text-sm font-bold text-white">Aprovar como membro</button></form><form method="post" action={`/api/admin/usuarios/${user.id}/rejeitar`}><button className="rounded-xl border border-red-300 px-4 py-2 text-sm font-bold text-red-700">Rejeitar</button></form></div></div></article>) : <p className="rounded-2xl border border-[#d5e3ec] bg-white p-6">Nenhum cadastro pendente.</p>}</div>

      <h2 className="mt-12 text-2xl font-bold text-[#17375e]">Recuperações de senha</h2><div className="mt-5 grid gap-4">{passwordRequests.length ? passwordRequests.map((request) => <article key={request.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#d5e3ec] bg-white p-5"><div><h3 className="font-bold text-[#17375e]">{request.fullName}</h3><p className="text-sm">{request.email} · solicitada em {new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Cuiaba" }).format(new Date(request.requestedAt))}</p></div><div className="flex gap-2"><form method="post" action={`/api/admin/recuperacao/${request.id}/aprovar`}><button className="rounded-xl bg-[#315f7d] px-4 py-2 text-sm font-bold text-white">Validar nova senha</button></form><form method="post" action={`/api/admin/recuperacao/${request.id}/rejeitar`}><button className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold">Rejeitar</button></form></div></article>) : <p className="rounded-2xl border border-[#d5e3ec] bg-white p-6">Nenhuma recuperação pendente.</p>}</div>

      <h2 className="mt-12 text-2xl font-bold text-[#17375e]">Usuários cadastrados</h2><div className="mt-5 overflow-x-auto rounded-2xl border border-[#d5e3ec] bg-white"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-[#e8f2f8]"><tr><th className="p-4">Usuário</th><th className="p-4">Nível</th><th className="p-4">Situação</th><th className="p-4">Presidência</th><th className="p-4">Administração</th></tr></thead><tbody>{registered.map((user) => <tr key={user.id} className="border-t border-[#e2ebf1]"><td className="p-4"><strong className="block text-[#17375e]">{user.fullName}</strong><span>{user.email}</span></td><td className="p-4">{roleLabel(user.role)}</td><td className="p-4">{statusLabel[user.status]}</td><td className="p-4">{user.isCmsPresident ? "Presidente do CMS" : "—"}</td><td className="p-4">{session.role === "master" ? <form method="post" action={`/api/admin/usuarios/${user.id}/atualizar`} className="flex flex-wrap items-center gap-2"><select name="role" defaultValue={user.role} className="input py-2">{userRoles.map((role: UserRole) => <option key={role} value={role}>{roleLabel(role)}</option>)}</select><select name="status" defaultValue={user.status} className="input py-2"><option value="ativo">Ativo</option><option value="suspenso">Suspenso</option><option value="rejeitado">Rejeitado</option></select><label className="flex items-center gap-2 font-bold"><input type="checkbox" name="isPresident" defaultChecked={user.isCmsPresident} /> Presidente</label><button className="rounded-lg bg-[#315f7d] px-3 py-2 font-bold text-white">Salvar</button></form> : <span className="text-xs">Somente o master altera níveis.</span>}</td></tr>)}</tbody></table></div>
    </section>
  </main>;
}
