-- Plano de classificação documental preparado em 13/08/2026.
-- Não move, renomeia ou exclui arquivos do Google Drive.

BEGIN;

INSERT INTO document_classification_batches (
  id, scan_id, policy_drive_file_id, policy_title, policy_edition_year, status,
  document_count, misplaced_count, restricted_count,
  requires_policy_amendment_count, duplicate_file_count, movement_authorized, notes
)
SELECT '00000000-0000-4000-8000-000000000003', scan.id,
       '11PEcAoqx7hSgEY4uNXMcclsRCgy7iMVa', 'Política de Gestão Documental do CMS',
       2026, 'pending_directorate', 79, 43, 5, 9, 10, false,
       'Plano preparado para revisão da Diretoria. As pastas 13 e 14 dependem de alteração formal da Política.'
FROM drive_inventory_scans scan ORDER BY scan.scanned_at DESC LIMIT 1
ON CONFLICT (id) DO UPDATE SET
  scan_id = EXCLUDED.scan_id,
  document_count = EXCLUDED.document_count,
  misplaced_count = EXCLUDED.misplaced_count,
  restricted_count = EXCLUDED.restricted_count,
  requires_policy_amendment_count = EXCLUDED.requires_policy_amendment_count,
  duplicate_file_count = EXCLUDED.duplicate_file_count,
  notes = EXCLUDED.notes;

WITH source (
  drive_file_id, current_path, original_filename, classification_type,
  folder_code, recommended_folder, recommended_path, proposed_filename,
  subject, origin, recommended_visibility, classification_rationale,
  retention_rule, final_destination, requires_policy_amendment,
  duplicate_group, duplicate_disposition
) AS (VALUES
  ('1tmZElo64lp7LYx6hRnO_giRYuy7hSgvu', 'CMS Chapada dos Guimarães – Documentos Oficiais/00_Identidade Visual/Logo do Conselho Municipal de Saúde.jpeg', 'Logo do Conselho Municipal de Saúde.jpeg', 'Identidade Visual', '00', '00_Identidade Visual', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/00_Identidade Visual/IDENTIDADE_LOGO-DO-CONSELHO-MUNICIPAL-DE-SAUDE_DATA-A-CONFIRMAR_VIGENTE.jpeg', 'IDENTIDADE_LOGO-DO-CONSELHO-MUNICIPAL-DE-SAUDE_DATA-A-CONFIRMAR_VIGENTE.jpeg', 'Logo do Conselho Municipal de Saúde', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Enquanto vigente', 'Eliminar versão obsoleta mediante termo', false, 'logo-cms', 'official_exemplar'),
  ('12bhEy7wixvaGSYSGzYZ73Zt2fB0M-PCu', 'CMS Chapada dos Guimarães – Documentos Oficiais/01_Modelos Oficiais/CNS publica documento com perguntas e respostas para a realização das etapas municipais da 18ª CNS — Conselho Nacional de Saúde.pdf', 'CNS publica documento com perguntas e respostas para a realização das etapas municipais da 18ª CNS — Conselho Nacional de Saúde.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/NORMA_CNS-PUBLICA-DOCUMENTO-COM-PERGUNTAS-E-RESPOSTAS-PARA-A-REALIZACAO-DAS-ETAPAS-MUNICIPAIS-DA-18-CNS-CO_DATA-A-CONFIRMAR_PUB.pdf', 'NORMA_CNS-PUBLICA-DOCUMENTO-COM-PERGUNTAS-E-RESPOSTAS-PARA-A-REALIZACAO-DAS-ETAPAS-MUNICIPAIS-DA-18-CNS-CO_DATA-A-CONFIRMAR_PUB.pdf', 'CNS publica documento com perguntas e respostas para a realização das etapas municipais da 18ª CNS — Conselho Nacional de Saúde', 'Conselho Nacional de Saúde', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1EqXV797Pj3BT9jDCgD5sI8X3JBbC89En', 'CMS Chapada dos Guimarães – Documentos Oficiais/01_Modelos Oficiais/CONSELHO MUNICIPAL DE SAÚDE DE CHAPADA DOS GUIMARÃES.docx', 'CONSELHO MUNICIPAL DE SAÚDE DE CHAPADA DOS GUIMARÃES.docx', 'Modelo Oficial', '01', '01_Modelos Oficiais', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/01_Modelos Oficiais/MODELO_CONSELHO-MUNICIPAL-DE-SAUDE-DE-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VIGENTE.docx', 'MODELO_CONSELHO-MUNICIPAL-DE-SAUDE-DE-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VIGENTE.docx', 'CONSELHO MUNICIPAL DE SAÚDE DE CHAPADA DOS GUIMARÃES', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Enquanto vigente', 'Eliminar versão obsoleta mediante termo', false, NULL, 'not_applicable'),
  ('1CVnIYGQ3GgZ5sgKZ4aWDs5pooqqNPIif', 'CMS Chapada dos Guimarães – Documentos Oficiais/01_Modelos Oficiais/Conselhos-municipais-de-politicas-publicas-e-a-atuacao-do-MP.pdf', 'Conselhos-municipais-de-politicas-publicas-e-a-atuacao-do-MP.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/NORMA_CONSELHOS-MUNICIPAIS-DE-POLITICAS-PUBLICAS-E-A-ATUACAO-DO-MP_DATA-A-CONFIRMAR_PUB.pdf', 'NORMA_CONSELHOS-MUNICIPAIS-DE-POLITICAS-PUBLICAS-E-A-ATUACAO-DO-MP_DATA-A-CONFIRMAR_PUB.pdf', 'Conselhos-municipais-de-politicas-publicas-e-a-atuacao-do-MP', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1bc9bBOqbokd1YWyHYc8wvFArsWdvARCe', 'CMS Chapada dos Guimarães – Documentos Oficiais/01_Modelos Oficiais/Lei Ordinária 779 1997 de Chapada dos Guimarães MT.pdf', 'Lei Ordinária 779 1997 de Chapada dos Guimarães MT.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/LEI_LEI-ORDINARIA-779-1997-DE-CHAPADA-DOS-GUIMARAES-MT_DATA-A-CONFIRMAR_PUB.pdf', 'LEI_LEI-ORDINARIA-779-1997-DE-CHAPADA-DOS-GUIMARAES-MT_DATA-A-CONFIRMAR_PUB.pdf', 'Lei Ordinária 779 1997 de Chapada dos Guimarães MT', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1XsZpZhQdQqsaRHc9gNSvvGLei70gowBS', 'CMS Chapada dos Guimarães – Documentos Oficiais/01_Modelos Oficiais/LEI_Nº_572-1991.pdf', 'LEI_Nº_572-1991.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/LEI_LEI-N-572-1991_DATA-A-CONFIRMAR_PUB.pdf', 'LEI_LEI-N-572-1991_DATA-A-CONFIRMAR_PUB.pdf', 'LEI_Nº_572-1991', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('159s1_fWboi0yP2GxwQfGxJXnBACTnrK8', 'CMS Chapada dos Guimarães – Documentos Oficiais/01_Modelos Oficiais/logo_cms.jpeg', 'logo_cms.jpeg', 'Identidade Visual', '00', '00_Identidade Visual', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/00_Identidade Visual/IDENTIDADE_LOGO-CMS_DATA-A-CONFIRMAR_VIGENTE.jpeg', 'IDENTIDADE_LOGO-CMS_DATA-A-CONFIRMAR_VIGENTE.jpeg', 'logo_cms', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'public', 'O conteúdo e o nome indicam a classe 00_Identidade Visual; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente', 'Eliminar versão obsoleta mediante termo', false, 'logo-cms', 'secondary_copy'),
  ('15byNO8FRGZGpefBHE-_Q6YoT9x8KhWGo', 'CMS Chapada dos Guimarães – Documentos Oficiais/01_Modelos Oficiais/OFÍCIO 029-2026 - CMS Chapada dos Guimaraes.pdf', 'OFÍCIO 029-2026 - CMS Chapada dos Guimaraes.pdf', 'Ofício Expedido', '03', '03_Ofícios', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/03_Ofícios/2026/OFICIO_OFICIO-029-2026-CMS-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'OFICIO_OFICIO-029-2026-CMS-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'OFÍCIO 029-2026 - CMS Chapada dos Guimaraes', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'O conteúdo e o nome indicam a classe 03_Ofícios; o local atual não corresponde à destinação prevista na Política.', '2 anos correntes + 3 anos intermediários', 'Eliminar, salvo se vinculado a resolução ou processo permanente', false, 'oficio-029', 'official_exemplar'),
  ('1Fs4TwdXn96jMsgOCMRM29FYp491qQNoT', 'CMS Chapada dos Guimarães – Documentos Oficiais/01_Modelos Oficiais/REGIMENTO INTERNO Conselho Municipal de Saúde - 11-02-2016 (1).pdf', 'REGIMENTO INTERNO Conselho Municipal de Saúde - 11-02-2016 (1).pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/REGIMENTO_REGIMENTO-INTERNO-CONSELHO-MUNICIPAL-DE-SAUDE-11-02-2016-1_11-02-2016_PUB.pdf', 'REGIMENTO_REGIMENTO-INTERNO-CONSELHO-MUNICIPAL-DE-SAUDE-11-02-2016-1_11-02-2016_PUB.pdf', 'REGIMENTO INTERNO Conselho Municipal de Saúde - 11-02-2016 (1)', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1u-d85ZkpEssW9Ggn6031E5YE8ZqrodsX', 'CMS Chapada dos Guimarães – Documentos Oficiais/03_Ofícios/Oficio 337-2026 resolução- CORRE (1).doc', 'Oficio 337-2026 resolução- CORRE (1).doc', 'Ofício Expedido', '03', '03_Ofícios', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/03_Ofícios/2026/OFICIO_OFICIO-337-2026-RESOLUCAO-CORRE-1_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.doc', 'OFICIO_OFICIO-337-2026-RESOLUCAO-CORRE-1_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.doc', 'Oficio 337-2026 resolução- CORRE (1)', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', '2 anos correntes + 3 anos intermediários', 'Eliminar, salvo se vinculado a resolução ou processo permanente', false, NULL, 'not_applicable'),
  ('1uCuwrnZjadlBQURhXvGa8KVMDuNHQpOZ', 'CMS Chapada dos Guimarães – Documentos Oficiais/03_Ofícios/Parecer Juridico Procuradoria_0001.pdf', 'Parecer Juridico Procuradoria_0001.pdf', 'Parecer Técnico ou Jurídico', '05', '05_Pareceres', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/05_Pareceres/2026/PARECER_PARECER-JURIDICO-PROCURADORIA-0001_DATA-A-CONFIRMAR_RESTRITO.pdf', 'PARECER_PARECER-JURIDICO-PROCURADORIA-0001_DATA-A-CONFIRMAR_RESTRITO.pdf', 'Parecer Juridico Procuradoria_0001', 'Procuradoria Jurídica', 'restricted', 'O conteúdo e o nome indicam a classe 05_Pareceres; o local atual não corresponde à destinação prevista na Política.', '5 anos correntes + 5 anos intermediários', 'Guarda permanente quando vinculado a contas, planos ou deliberação', false, NULL, 'not_applicable'),
  ('13kii43EWhoMVQ-rn1E5Mj-tSnwuAeCiTuJi4YRwEDJU', 'CMS Chapada dos Guimarães – Documentos Oficiais/06_Atas/Documento sem título', 'Documento sem título', 'Ata de Reunião', '06', '06_Atas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/06_Atas/2026/ATA_DOCUMENTO-SEM-TITULO_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR', 'ATA_DOCUMENTO-SEM-TITULO_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR', 'Ata da reunião do CMS de 12 de maio de 2026', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Mandato vigente', 'Guarda permanente', false, NULL, 'not_applicable'),
  ('1i-pRYO-9QoAfUb4uCEXalLCpnC8iRsSV', 'CMS Chapada dos Guimarães – Documentos Oficiais/06_Atas/Modelo Ata Cms Chapada Dos Guimaraes.docx', 'Modelo Ata Cms Chapada Dos Guimaraes.docx', 'Modelo Oficial', '01', '01_Modelos Oficiais', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/01_Modelos Oficiais/MODELO_MODELO-ATA-CMS-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VIGENTE.docx', 'MODELO_MODELO-ATA-CMS-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VIGENTE.docx', 'Modelo Ata Cms Chapada Dos Guimaraes', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'O conteúdo e o nome indicam a classe 01_Modelos Oficiais; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente', 'Eliminar versão obsoleta mediante termo', false, NULL, 'not_applicable'),
  ('1Dd6BoPLUobkJNn1_Ha7Sn9SJJ9bh0fb3', 'CMS Chapada dos Guimarães – Documentos Oficiais/07_Recomendações/Orientações/Orientacoes_conselheiros_saude_1_edicao_b8ee038ab9.pdf', 'Orientacoes_conselheiros_saude_1_edicao_b8ee038ab9.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/ORIENTACAO_ORIENTACOES-CONSELHEIROS-SAUDE-1-EDICAO-B8EE038AB9_DATA-A-CONFIRMAR_PUB.pdf', 'ORIENTACAO_ORIENTACOES-CONSELHEIROS-SAUDE-1-EDICAO-B8EE038AB9_DATA-A-CONFIRMAR_PUB.pdf', 'Orientacoes_conselheiros_saude_1_edicao_b8ee038ab9', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, 'orientacoes-1', 'official_exemplar'),
  ('1K8u-fd1Jk2Q2r54dsCnpg_dPbc3tt6hq', 'CMS Chapada dos Guimarães – Documentos Oficiais/07_Recomendações/Orientações/Orientacoes_conselheiros_saude_2_edicao_d900e1d5ee.pdf', 'Orientacoes_conselheiros_saude_2_edicao_d900e1d5ee.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/ORIENTACAO_ORIENTACOES-CONSELHEIROS-SAUDE-2-EDICAO-D900E1D5EE_DATA-A-CONFIRMAR_PUB.pdf', 'ORIENTACAO_ORIENTACOES-CONSELHEIROS-SAUDE-2-EDICAO-D900E1D5EE_DATA-A-CONFIRMAR_PUB.pdf', 'Orientacoes_conselheiros_saude_2_edicao_d900e1d5ee', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, 'orientacoes-2', 'official_exemplar'),
  ('1bxRgBqj404CTQQd-lQW_jh7gCxMhfdsG', 'CMS Chapada dos Guimarães – Documentos Oficiais/07_Recomendações/Orientações/TCU_Orientacoes_para_conselheiros_de_saude_V2_WEB_2_compressed_a9dcb8bb35.pdf', 'TCU_Orientacoes_para_conselheiros_de_saude_V2_WEB_2_compressed_a9dcb8bb35.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/ORIENTACAO_TCU-ORIENTACOES-PARA-CONSELHEIROS-DE-SAUDE-V2-WEB-2-COMPRESSED-A9DCB8BB35_DATA-A-CONFIRMAR_PUB.pdf', 'ORIENTACAO_TCU-ORIENTACOES-PARA-CONSELHEIROS-DE-SAUDE-V2-WEB-2-COMPRESSED-A9DCB8BB35_DATA-A-CONFIRMAR_PUB.pdf', 'TCU_Orientacoes_para_conselheiros_de_saude_V2_WEB_2_compressed_a9dcb8bb35', 'Tribunal de Contas da União', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, 'tcu-orientacoes', 'official_exemplar'),
  ('1MygMfiTUijOIvRLyf-6TZO_1FiX3XGtq', 'CMS Chapada dos Guimarães – Documentos Oficiais/09_Legislação e Normas/LegislacaoCitada-PL-6507-2009.pdf', 'LegislacaoCitada-PL-6507-2009.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/NORMA_LEGISLACAOCITADA-PL-6507-2009_DATA-A-CONFIRMAR_PUB.pdf', 'NORMA_LEGISLACAOCITADA-PL-6507-2009_DATA-A-CONFIRMAR_PUB.pdf', 'LegislacaoCitada-PL-6507-2009', 'Origem a confirmar na revisão da Diretoria', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1lMh6C9cPrVzDWWREPO5RJYxD9BMU02pl', 'CMS Chapada dos Guimarães – Documentos Oficiais/09_Legislação e Normas/lei-8080-19-setembro-1990-365093-normaatualizada-pl.pdf', 'lei-8080-19-setembro-1990-365093-normaatualizada-pl.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/LEI_LEI-8080-19-SETEMBRO-1990-365093-NORMAATUALIZADA-PL_DATA-A-CONFIRMAR_PUB.pdf', 'LEI_LEI-8080-19-SETEMBRO-1990-365093-NORMAATUALIZADA-PL_DATA-A-CONFIRMAR_PUB.pdf', 'lei-8080-19-setembro-1990-365093-normaatualizada-pl', 'Origem a confirmar na revisão da Diretoria', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1fTg4tXYQC2l2O62-OjA8j1nU7e0KcrNi', 'CMS Chapada dos Guimarães – Documentos Oficiais/10_Documentos Recebidos/Convite_TCE.pdf', 'Convite_TCE.pdf', 'Documento Recebido', '10', '10_Documentos Recebidos', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/10_Documentos Recebidos/2026/RECEBIDO_CONVITE-TCE_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'RECEBIDO_CONVITE-TCE_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'Convite_TCE', 'Tribunal de Contas do Estado', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', '2 anos correntes + 3 anos intermediários', 'Eliminar, salvo se vinculado a deliberação ou processo permanente', false, NULL, 'not_applicable'),
  ('12csM_4ooBEx-m5WCyG8Ro2dBofx2GgiX', 'CMS Chapada dos Guimarães – Documentos Oficiais/10_Documentos Recebidos/OFÍCIO 029-2026 - CMS Chapada dos Guimaraes.pdf', 'OFÍCIO 029-2026 - CMS Chapada dos Guimaraes.pdf', 'Ofício Expedido', '03', '03_Ofícios', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/03_Ofícios/2026/OFICIO_OFICIO-029-2026-CMS-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'OFICIO_OFICIO-029-2026-CMS-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'OFÍCIO 029-2026 - CMS Chapada dos Guimaraes', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'O conteúdo e o nome indicam a classe 03_Ofícios; o local atual não corresponde à destinação prevista na Política.', '2 anos correntes + 3 anos intermediários', 'Eliminar, salvo se vinculado a resolução ou processo permanente', false, 'oficio-029', 'secondary_copy'),
  ('1NWmFBoZVQ9zg-TT-_3J9U3nWmxWZVSWK', 'CMS Chapada dos Guimarães – Documentos Oficiais/10_Documentos Recebidos/PAS 2026 CHAPADA.pdf', 'PAS 2026 CHAPADA.pdf', 'Instrumento de Planejamento e Gestão', '14', '14_Planejamento e Gestão do SUS', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/14_Planejamento e Gestão do SUS/2026/PAS_PAS-2026-CHAPADA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'PAS_PAS-2026-CHAPADA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'PAS 2026 CHAPADA', 'Secretaria Municipal de Saúde de Chapada dos Guimarães', 'public', 'O conteúdo e o nome indicam a classe 14_Planejamento e Gestão do SUS; o local atual não corresponde à destinação prevista na Política.', 'Vigência do instrumento + ciclo de prestação de contas', 'Guarda permanente dos instrumentos aprovados', true, NULL, 'not_applicable'),
  ('16EDYbzRKwxiZigHRjSUEJK_LGqPDFvAP', 'CMS Chapada dos Guimarães – Documentos Oficiais/10_Documentos Recebidos/PMS CHAPADA 26-29 FINALIZADO.pdf', 'PMS CHAPADA 26-29 FINALIZADO.pdf', 'Instrumento de Planejamento e Gestão', '14', '14_Planejamento e Gestão do SUS', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/14_Planejamento e Gestão do SUS/2026/PMS_PMS-CHAPADA-26-29-FINALIZADO_DATA-A-CONFIRMAR_VF.pdf', 'PMS_PMS-CHAPADA-26-29-FINALIZADO_DATA-A-CONFIRMAR_VF.pdf', 'PMS CHAPADA 26-29 FINALIZADO', 'Secretaria Municipal de Saúde de Chapada dos Guimarães', 'public', 'O conteúdo e o nome indicam a classe 14_Planejamento e Gestão do SUS; o local atual não corresponde à destinação prevista na Política.', 'Vigência do instrumento + ciclo de prestação de contas', 'Guarda permanente dos instrumentos aprovados', true, NULL, 'not_applicable'),
  ('1PcCI1FMv-9az-rqSbMRaCY5WflROwfeV', 'CMS Chapada dos Guimarães – Documentos Oficiais/10_Documentos Recebidos/Projeto emenda estadual - 25 Paulo Araujo  200 Mil.docx', 'Projeto emenda estadual - 25 Paulo Araujo  200 Mil.docx', 'Instrumento de Planejamento e Gestão', '14', '14_Planejamento e Gestão do SUS', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/14_Planejamento e Gestão do SUS/2026/PLANEJAMENTO_PROJETO-EMENDA-ESTADUAL-25-PAULO-ARAUJO-200-MIL_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'PLANEJAMENTO_PROJETO-EMENDA-ESTADUAL-25-PAULO-ARAUJO-200-MIL_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'Projeto emenda estadual - 25 Paulo Araujo  200 Mil', 'Origem a confirmar na revisão da Diretoria', 'internal', 'O conteúdo e o nome indicam a classe 14_Planejamento e Gestão do SUS; o local atual não corresponde à destinação prevista na Política.', 'Vigência do instrumento + ciclo de prestação de contas', 'Guarda permanente dos instrumentos aprovados', true, NULL, 'not_applicable'),
  ('1M9rw_m39nY6EzDBPWe1nFxYb2pOXgeik', 'CMS Chapada dos Guimarães – Documentos Oficiais/10_Documentos Recebidos/proposta-11730899000126003 (4).pdf', 'proposta-11730899000126003 (4).pdf', 'Instrumento de Planejamento e Gestão', '14', '14_Planejamento e Gestão do SUS', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/14_Planejamento e Gestão do SUS/2026/PLANEJAMENTO_PROPOSTA-11730899000126003-4_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'PLANEJAMENTO_PROPOSTA-11730899000126003-4_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'proposta-11730899000126003 (4)', 'Ministério da Saúde / Fundo Nacional de Saúde', 'internal', 'O conteúdo e o nome indicam a classe 14_Planejamento e Gestão do SUS; o local atual não corresponde à destinação prevista na Política.', 'Vigência do instrumento + ciclo de prestação de contas', 'Guarda permanente dos instrumentos aprovados', true, NULL, 'not_applicable'),
  ('1wNoNz0yACi9kOotiKsf-unhrHgIE0dM5', 'CMS Chapada dos Guimarães – Documentos Oficiais/10_Documentos Recebidos/proposta-11730899000126005 (2).pdf', 'proposta-11730899000126005 (2).pdf', 'Instrumento de Planejamento e Gestão', '14', '14_Planejamento e Gestão do SUS', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/14_Planejamento e Gestão do SUS/2026/PLANEJAMENTO_PROPOSTA-11730899000126005-2_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'PLANEJAMENTO_PROPOSTA-11730899000126005-2_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'proposta-11730899000126005 (2)', 'Ministério da Saúde / Fundo Nacional de Saúde', 'internal', 'O conteúdo e o nome indicam a classe 14_Planejamento e Gestão do SUS; o local atual não corresponde à destinação prevista na Política.', 'Vigência do instrumento + ciclo de prestação de contas', 'Guarda permanente dos instrumentos aprovados', true, NULL, 'not_applicable'),
  ('1aLKysZStITvphMcAxde84WU6eY-6WW4M', 'CMS Chapada dos Guimarães – Documentos Oficiais/10_Documentos Recebidos/proposta-11730899000126006 (1).pdf', 'proposta-11730899000126006 (1).pdf', 'Instrumento de Planejamento e Gestão', '14', '14_Planejamento e Gestão do SUS', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/14_Planejamento e Gestão do SUS/2026/PLANEJAMENTO_PROPOSTA-11730899000126006-1_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'PLANEJAMENTO_PROPOSTA-11730899000126006-1_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'proposta-11730899000126006 (1)', 'Ministério da Saúde / Fundo Nacional de Saúde', 'internal', 'O conteúdo e o nome indicam a classe 14_Planejamento e Gestão do SUS; o local atual não corresponde à destinação prevista na Política.', 'Vigência do instrumento + ciclo de prestação de contas', 'Guarda permanente dos instrumentos aprovados', true, NULL, 'not_applicable'),
  ('1G9rCmLUVTxhv-WkefOARnkyAlXOZjAKa', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/18ª CNS.pdf', '18ª CNS.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_18-CNS_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'CONFERENCIA_18-CNS_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', '18ª CNS', 'Conselho Nacional de Saúde', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1y5N5F2oX6SoWwfIP8-lNgGgwa1ChvD5X', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/CMS_conferencia.pptx', 'CMS_conferencia.pptx', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_CMS-CONFERENCIA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pptx', 'CONFERENCIA_CMS-CONFERENCIA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pptx', 'CMS_conferencia', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1F6Vxa8PekgxgxNkB1LQofUyYhZhjRAp5wWIC4lZSc9I', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/Convite_9ª Conferência', 'Convite_9ª Conferência', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_CONVITE-9-CONFERENCIA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR', 'CONFERENCIA_CONVITE-9-CONFERENCIA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR', 'Convite_9ª Conferência', 'Comissão Organizadora da Conferência / CMS', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1eNwwWTJDKXZ1JduOEqyOFCgp2HK_2aVU', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/CONVOCAÇÃO Nº 001.pdf', 'CONVOCAÇÃO Nº 001.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_CONVOCACAO-N-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'CONFERENCIA_CONVOCACAO-N-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'CONVOCAÇÃO Nº 001', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('18uotI_pliIqFkny_vom_rT3TUsGlrpKq', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/Arquivos_Vetoriais/Arquivos vetoriais-20260518T183524Z-3-001.zip', 'Arquivos vetoriais-20260518T183524Z-3-001.zip', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_ARQUIVOS-VETORIAIS-20260518T183524Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'CONFERENCIA_ARQUIVOS-VETORIAIS-20260518T183524Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'Arquivos vetoriais-20260518T183524Z-3-001', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('185YrcsVtscVfPM8cmuVxzlSUTanhG6M1', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/Bases para PPT-20260518T183513Z-3-001.zip', 'Bases para PPT-20260518T183513Z-3-001.zip', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_BASES-PARA-PPT-20260518T183513Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'CONFERENCIA_BASES-PARA-PPT-20260518T183513Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'Bases para PPT-20260518T183513Z-3-001', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1vrG1Y4Xp3Y5ZjkIcOjYiE27kRGaJ-IIa', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/cns-no-805-dispoe-sobre-o-regimento-interno-e-as-diretriz-metodologicas-da-18a-conferencia-nacional-de-saude-docx-1.pdf', 'cns-no-805-dispoe-sobre-o-regimento-interno-e-as-diretriz-metodologicas-da-18a-conferencia-nacional-de-saude-docx-1.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_CNS-NO-805-DISPOE-SOBRE-O-REGIMENTO-INTERNO-E-AS-DIRETRIZ-METODOLOGICAS-DA-18A-CONFERENCIA-NACIONAL-_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'CONFERENCIA_CNS-NO-805-DISPOE-SOBRE-O-REGIMENTO-INTERNO-E-AS-DIRETRIZ-METODOLOGICAS-DA-18A-CONFERENCIA-NACIONAL-_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'cns-no-805-dispoe-sobre-o-regimento-interno-e-as-diretriz-metodologicas-da-18a-conferencia-nacional-de-saude-docx-1', 'Conselho Nacional de Saúde', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('17eNZJsmeYG-XJq75krGbhLrMLAq3zo6n', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/Fundos e bases para peças digitais-20260518T183515Z-3-001.zip', 'Fundos e bases para peças digitais-20260518T183515Z-3-001.zip', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_FUNDOS-E-BASES-PARA-PECAS-DIGITAIS-20260518T183515Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'CONFERENCIA_FUNDOS-E-BASES-PARA-PECAS-DIGITAIS-20260518T183515Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'Fundos e bases para peças digitais-20260518T183515Z-3-001', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('10__P0Q_XgBdkaFG-MGD3ZRJbasndbwBm', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/Imagem/Arquivos em PNG - Exclusivamente para uso digital-20260518T183520Z-3-001.zip', 'Arquivos em PNG - Exclusivamente para uso digital-20260518T183520Z-3-001.zip', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_ARQUIVOS-EM-PNG-EXCLUSIVAMENTE-PARA-USO-DIGITAL-20260518T183520Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'CONFERENCIA_ARQUIVOS-EM-PNG-EXCLUSIVAMENTE-PARA-USO-DIGITAL-20260518T183520Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'Arquivos em PNG - Exclusivamente para uso digital-20260518T183520Z-3-001', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('11uSxKtL3TcEX6uBpHKRPXaHJX_BObmPm', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/minuta-resolucao-cns-no-800-que-dispoe-sobre-a-alteracao-do-calendario-da-18a-cns-1-1-reparado-1.pdf', 'minuta-resolucao-cns-no-800-que-dispoe-sobre-a-alteracao-do-calendario-da-18a-cns-1-1-reparado-1.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_MINUTA-RESOLUCAO-CNS-NO-800-QUE-DISPOE-SOBRE-A-ALTERACAO-DO-CALENDARIO-DA-18A-CNS-1-1-REPARADO-1_DATA-A-CONFIRMAR_MIN.pdf', 'CONFERENCIA_MINUTA-RESOLUCAO-CNS-NO-800-QUE-DISPOE-SOBRE-A-ALTERACAO-DO-CALENDARIO-DA-18A-CNS-1-1-REPARADO-1_DATA-A-CONFIRMAR_MIN.pdf', 'minuta-resolucao-cns-no-800-que-dispoe-sobre-a-alteracao-do-calendario-da-18a-cns-1-1-reparado-1', 'Conselho Nacional de Saúde', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('198VHwshL477afLQZYOWNSPXJdgdNfgD4', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/minuta-resolucao-cns-no-801-dispoe-sobre-comissao-organizadora-da-18a-conferencia-nacional-de-saude.pdf', 'minuta-resolucao-cns-no-801-dispoe-sobre-comissao-organizadora-da-18a-conferencia-nacional-de-saude.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_MINUTA-RESOLUCAO-CNS-NO-801-DISPOE-SOBRE-COMISSAO-ORGANIZADORA-DA-18A-CONFERENCIA-NACIONAL-DE-SAUDE_DATA-A-CONFIRMAR_MIN.pdf', 'CONFERENCIA_MINUTA-RESOLUCAO-CNS-NO-801-DISPOE-SOBRE-COMISSAO-ORGANIZADORA-DA-18A-CONFERENCIA-NACIONAL-DE-SAUDE_DATA-A-CONFIRMAR_MIN.pdf', 'minuta-resolucao-cns-no-801-dispoe-sobre-comissao-organizadora-da-18a-conferencia-nacional-de-saude', 'Conselho Nacional de Saúde', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('13_N3jIs7_1qSVmhJVCMbrNL08dpbz1TR', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/resolucao-no-797-de-9-de-outubro-de-2025.pdf', 'resolucao-no-797-de-9-de-outubro-de-2025.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_RESOLUCAO-NO-797-DE-9-DE-OUTUBRO-DE-2025_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'CONFERENCIA_RESOLUCAO-NO-797-DE-9-DE-OUTUBRO-DE-2025_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'resolucao-no-797-de-9-de-outubro-de-2025', 'Comissão Organizadora da Conferência / CMS', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1CCf4xB6q0a8_c0DX_nB1zKE6X3xbJ8hN', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/resolucao-no-804-de-12-de-marco-de-2026.pdf', 'resolucao-no-804-de-12-de-marco-de-2026.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_RESOLUCAO-NO-804-DE-12-DE-MARCO-DE-2026_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'CONFERENCIA_RESOLUCAO-NO-804-DE-12-DE-MARCO-DE-2026_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'resolucao-no-804-de-12-de-marco-de-2026', 'Comissão Organizadora da Conferência / CMS', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1zMzKwqfQA6kD-IvVHmjRZAIC7OAMnhHy', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/DOC_18ªCNS/Uso da Marca/Manual básico de uso da marca-20260518T183535Z-3-001.zip', 'Manual básico de uso da marca-20260518T183535Z-3-001.zip', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_MANUAL-BASICO-DE-USO-DA-MARCA-20260518T183535Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'CONFERENCIA_MANUAL-BASICO-DE-USO-DA-MARCA-20260518T183535Z-3-001_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.zip', 'Manual básico de uso da marca-20260518T183535Z-3-001', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1J-Iu7gCiiu6iD8ikB74iS_FGieVbfGYv', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/documentos/ganbatte_final_completo.mp4', 'ganbatte_final_completo.mp4', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_GANBATTE-FINAL-COMPLETO_DATA-A-CONFIRMAR_VF.mp4', 'CONFERENCIA_GANBATTE-FINAL-COMPLETO_DATA-A-CONFIRMAR_VF.mp4', 'ganbatte_final_completo', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1pvgPRCCxQIlhD2ApUaaqnSttFfwL8YTO', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/documentos/O cuidado faz a diferença.mp4', 'O cuidado faz a diferença.mp4', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_O-CUIDADO-FAZ-A-DIFERENCA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.mp4', 'CONFERENCIA_O-CUIDADO-FAZ-A-DIFERENCA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.mp4', 'O cuidado faz a diferença', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1AwbglUqzAOOFfhj4Cjp8KQlOhYkMim3T', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/documentos/Pré Conferência (respostas).xlsx', 'Pré Conferência (respostas).xlsx', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_PRE-CONFERENCIA-RESPOSTAS_DATA-A-CONFIRMAR_RESTRITO.xlsx', 'CONFERENCIA_PRE-CONFERENCIA-RESPOSTAS_DATA-A-CONFIRMAR_RESTRITO.xlsx', 'Respostas da pré-conferência com dados pessoais de participantes', 'Comissão Organizadora da Conferência / CMS', 'restricted', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1rYYFYJZTqWGqWlcw8e0gFagIMDdvke2L', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/documentos/PROGRAMAÇÃO.docx', 'PROGRAMAÇÃO.docx', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_PROGRAMACAO_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'CONFERENCIA_PROGRAMACAO_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'PROGRAMAÇÃO', 'Comissão Organizadora da Conferência / CMS', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1ASPQ4nlV_NsxkxI9kvRSgbLl8TwIxagB', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/documentos/propostas_grupos_trabalho_integra.docx', 'propostas_grupos_trabalho_integra.docx', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_PROPOSTAS-GRUPOS-TRABALHO-INTEGRA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'CONFERENCIA_PROPOSTAS-GRUPOS-TRABALHO-INTEGRA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'propostas_grupos_trabalho_integra', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1hHNaxYFH702bKJ9fIm0tkUIlnk9SL440', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/documentos/propostas_por_eixo.pdf', 'propostas_por_eixo.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_PROPOSTAS-POR-EIXO_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'CONFERENCIA_PROPOSTAS-POR-EIXO_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'propostas_por_eixo', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1aAKL8UUzFL5ocUYLjVMrMBYa-NZ18pjP', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/documentos/REGIMENTO INTERNO DA 8ª CONFERÊNCIA MUNICIPAL DE SAÚDE aprovado CMS.pdf', 'REGIMENTO INTERNO DA 8ª CONFERÊNCIA MUNICIPAL DE SAÚDE aprovado CMS.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_REGIMENTO-INTERNO-DA-8-CONFERENCIA-MUNICIPAL-DE-SAUDE-APROVADO-CMS_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'CONFERENCIA_REGIMENTO-INTERNO-DA-8-CONFERENCIA-MUNICIPAL-DE-SAUDE-APROVADO-CMS_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'REGIMENTO INTERNO DA 8ª CONFERÊNCIA MUNICIPAL DE SAÚDE aprovado CMS', 'Comissão Organizadora da Conferência / CMS', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1lIaATmQFUO3Jjwg0p8kAW1J-hF5pPe8z', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/IX_Conferência_Municipal_de_Saúde_-_Chapada_dos_Guimarães.pptx', 'IX_Conferência_Municipal_de_Saúde_-_Chapada_dos_Guimarães.pptx', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_IX-CONFERENCIA-MUNICIPAL-DE-SAUDE-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pptx', 'CONFERENCIA_IX-CONFERENCIA-MUNICIPAL-DE-SAUDE-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pptx', 'IX_Conferência_Municipal_de_Saúde_-_Chapada_dos_Guimarães', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1J5rZ84xM71-XWBQQ3nOsTNwEOrL1ML_T', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/Oficio_apoio_conferencia.jpeg', 'Oficio_apoio_conferencia.jpeg', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_OFICIO-APOIO-CONFERENCIA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.jpeg', 'CONFERENCIA_OFICIO-APOIO-CONFERENCIA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.jpeg', 'Oficio_apoio_conferencia', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1etql4oXzXsv2DOq_c0Q3tnoBDutCAmB1HulVr48Frl0', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/Pré Conferência', 'Pré Conferência', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_PRE-CONFERENCIA_DATA-A-CONFIRMAR_RESTRITO', 'CONFERENCIA_PRE-CONFERENCIA_DATA-A-CONFIRMAR_RESTRITO', 'Formulário de coleta de contribuições da pré-conferência', 'Comissão Organizadora da Conferência / CMS', 'restricted', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1zG46_baHqKj9C5PHJNBrzDAZXdKsu5Gn', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/Pre Conferência de Saúde - Chapada dos Guimarães.docx', 'Pre Conferência de Saúde - Chapada dos Guimarães.docx', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_PRE-CONFERENCIA-DE-SAUDE-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'CONFERENCIA_PRE-CONFERENCIA-DE-SAUDE-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'Pre Conferência de Saúde - Chapada dos Guimarães', 'Comissão Organizadora da Conferência / CMS', 'internal', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1KdLJxtmKFIZBEupTJLgeWhYqrvVlwSbRLDKUedOMsls', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/Pré Conferência_resumo', 'Pré Conferência_resumo', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_PRE-CONFERENCIA-RESUMO_DATA-A-CONFIRMAR_RESTRITO', 'CONFERENCIA_PRE-CONFERENCIA-RESUMO_DATA-A-CONFIRMAR_RESTRITO', 'Contribuições da pré-conferência com dados pessoais de participantes', 'Comissão Organizadora da Conferência / CMS', 'restricted', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1Uu_i9v_xd2ta3gz2WKvozweqTeh1YXB8RvUVRU-L-Jg', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/QRcode01', 'QRcode01', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_QRCODE01_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR', 'CONFERENCIA_QRCODE01_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR', 'QRcode01', 'Comissão Organizadora da Conferência / CMS', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('12zTnWOVgq5glmwz05jt6agL38c_L6jGA', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/Relatorio_9a_Conferencia_Municipal_de_Saude_Revisado_assinado.pdf', 'Relatorio_9a_Conferencia_Municipal_de_Saude_Revisado_assinado.pdf', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_RELATORIO-9A-CONFERENCIA-MUNICIPAL-DE-SAUDE-REVISADO-ASSINADO_DATA-A-CONFIRMAR_ASS.pdf', 'CONFERENCIA_RELATORIO-9A-CONFERENCIA-MUNICIPAL-DE-SAUDE-REVISADO-ASSINADO_DATA-A-CONFIRMAR_ASS.pdf', 'Relatorio_9a_Conferencia_Municipal_de_Saude_Revisado_assinado', 'Comissão Organizadora da Conferência / CMS', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('1qAGR0JBxsUcZbPvXHsEDEjqQfGfnCrC1', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/Relatorio_Final_9a_Conferencia_Municipal_de_Saude_Revisado.docx', 'Relatorio_Final_9a_Conferencia_Municipal_de_Saude_Revisado.docx', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_RELATORIO-FINAL-9A-CONFERENCIA-MUNICIPAL-DE-SAUDE-REVISADO_DATA-A-CONFIRMAR_VF.docx', 'CONFERENCIA_RELATORIO-FINAL-9A-CONFERENCIA-MUNICIPAL-DE-SAUDE-REVISADO_DATA-A-CONFIRMAR_VF.docx', 'Relatorio_Final_9a_Conferencia_Municipal_de_Saude_Revisado', 'Comissão Organizadora da Conferência / CMS', 'public', 'A classe atual coincide com a estrutura da Política; recomenda-se apenas padronizar nome e subpasta.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('15Hof7VTWCDiVieCpMn2r-fu3H6ZSrR9H', 'CMS Chapada dos Guimarães – Documentos Oficiais/12_Conferências/relatorio_ips_brasil_2026.pdf', 'relatorio_ips_brasil_2026.pdf', 'Instrumento de Planejamento e Gestão', '14', '14_Planejamento e Gestão do SUS', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/14_Planejamento e Gestão do SUS/2026/PLANEJAMENTO_RELATORIO-IPS-BRASIL-2026_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'PLANEJAMENTO_RELATORIO-IPS-BRASIL-2026_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'relatorio_ips_brasil_2026', 'Comissão Organizadora da Conferência / CMS', 'internal', 'O conteúdo e o nome indicam a classe 14_Planejamento e Gestão do SUS; o local atual não corresponde à destinação prevista na Política.', 'Vigência do instrumento + ciclo de prestação de contas', 'Guarda permanente dos instrumentos aprovados', true, NULL, 'not_applicable'),
  ('1K-wlfnfXR9AQgJj01tBOAL8YFazZakPk', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/ata-conselho05-2026-20260520142859-88a7b646.pdf', 'ata-conselho05-2026-20260520142859-88a7b646.pdf', 'Ata de Reunião', '06', '06_Atas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/06_Atas/2026/ATA_ATA-CONSELHO05-2026-20260520142859-88A7B646_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'ATA_ATA-CONSELHO05-2026-20260520142859-88A7B646_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.pdf', 'ata-conselho05-2026-20260520142859-88a7b646', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'O conteúdo e o nome indicam a classe 06_Atas; o local atual não corresponde à destinação prevista na Política.', 'Mandato vigente', 'Guarda permanente', false, NULL, 'not_applicable'),
  ('1WbTnYYwFA8HU3VO9QdhWPa29rtH8oe3F', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/auditoria_sna.pdf', 'auditoria_sna.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/NORMA_AUDITORIA-SNA_DATA-A-CONFIRMAR_PUB.pdf', 'NORMA_AUDITORIA-SNA_DATA-A-CONFIRMAR_PUB.pdf', 'auditoria_sna', 'Ministério da Saúde / DENASUS', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1bpNXUElPWvbJ8dW_qy8fm3poFj8ZJ3Ja', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/Lei Casa dos Conselhos.pdf', 'Lei Casa dos Conselhos.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/LEI_LEI-CASA-DOS-CONSELHOS_DATA-A-CONFIRMAR_PUB.pdf', 'LEI_LEI-CASA-DOS-CONSELHOS_DATA-A-CONFIRMAR_PUB.pdf', 'Lei Casa dos Conselhos', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1X_OjbZFDQSdJX9_2_7sA0U9T5ZmeHC4U', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/Lei-ordinaria-1362-2009-Chapada-dos-guimaraes-MT.pdf', 'Lei-ordinaria-1362-2009-Chapada-dos-guimaraes-MT.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/LEI_LEI-ORDINARIA-1362-2009-CHAPADA-DOS-GUIMARAES-MT_DATA-A-CONFIRMAR_PUB.pdf', 'LEI_LEI-ORDINARIA-1362-2009-CHAPADA-DOS-GUIMARAES-MT_DATA-A-CONFIRMAR_PUB.pdf', 'Lei-ordinaria-1362-2009-Chapada-dos-guimaraes-MT', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1gbjBhKyvYR6QalbG7-xsSVp-VoLAHo8B', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/Lei-ordinaria-6541-2014-Criciuma-SC.pdf', 'Lei-ordinaria-6541-2014-Criciuma-SC.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/LEI_LEI-ORDINARIA-6541-2014-CRICIUMA-SC_DATA-A-CONFIRMAR_PUB.pdf', 'LEI_LEI-ORDINARIA-6541-2014-CRICIUMA-SC_DATA-A-CONFIRMAR_PUB.pdf', 'Lei-ordinaria-6541-2014-Criciuma-SC', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1sCP_3WefcPAbPyASgJ0g7ZcXdNSurxBl', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/leicomplementar-141-13-janeiro-2012-612270-normaatualizada-pl.pdf', 'leicomplementar-141-13-janeiro-2012-612270-normaatualizada-pl.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/LEI_LEICOMPLEMENTAR-141-13-JANEIRO-2012-612270-NORMAATUALIZADA-PL_DATA-A-CONFIRMAR_PUB.pdf', 'LEI_LEICOMPLEMENTAR-141-13-JANEIRO-2012-612270-NORMAATUALIZADA-PL_DATA-A-CONFIRMAR_PUB.pdf', 'leicomplementar-141-13-janeiro-2012-612270-normaatualizada-pl', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1rryL9WUtV3ZSKOugipR3DY8yZ48iznUqhJjgeWBq0KM', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/MINUTA PRELIMINAR DE PROJETO DE LEI ORDINÁRIA CMS CHAPADA DOS GUIMARÃES', 'MINUTA PRELIMINAR DE PROJETO DE LEI ORDINÁRIA CMS CHAPADA DOS GUIMARÃES', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/NORMA_MINUTA-PRELIMINAR-DE-PROJETO-DE-LEI-ORDINARIA-CMS-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_MIN', 'NORMA_MINUTA-PRELIMINAR-DE-PROJETO-DE-LEI-ORDINARIA-CMS-CHAPADA-DOS-GUIMARAES_DATA-A-CONFIRMAR_MIN', 'MINUTA PRELIMINAR DE PROJETO DE LEI ORDINÁRIA CMS CHAPADA DOS GUIMARÃES', 'Origem a confirmar na revisão da Diretoria', 'internal', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1F2RdzbIBglx25RXggvHhFgreqF9TSSdr', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/Orientação aos Membros do Conselho Municipal de Saúde_0.pdf', 'Orientação aos Membros do Conselho Municipal de Saúde_0.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/ORIENTACAO_ORIENTACAO-AOS-MEMBROS-DO-CONSELHO-MUNICIPAL-DE-SAUDE-0_DATA-A-CONFIRMAR_PUB.pdf', 'ORIENTACAO_ORIENTACAO-AOS-MEMBROS-DO-CONSELHO-MUNICIPAL-DE-SAUDE-0_DATA-A-CONFIRMAR_PUB.pdf', 'Orientação aos Membros do Conselho Municipal de Saúde_0', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1Z3pha4rMpi5BZhlZwG5lbc02Wx5EgYyo', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/Orientacoes_conselheiros_saude_1_edicao.pdf', 'Orientacoes_conselheiros_saude_1_edicao.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/ORIENTACAO_ORIENTACOES-CONSELHEIROS-SAUDE-1-EDICAO_DATA-A-CONFIRMAR_PUB.pdf', 'ORIENTACAO_ORIENTACOES-CONSELHEIROS-SAUDE-1-EDICAO_DATA-A-CONFIRMAR_PUB.pdf', 'Orientacoes_conselheiros_saude_1_edicao', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, 'orientacoes-1', 'secondary_copy'),
  ('1u_qc5A3AwbcbX79uSUwkI3Pe7bQPOaY4', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/Orientacoes_conselheiros_saude_2_edicao.pdf', 'Orientacoes_conselheiros_saude_2_edicao.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/ORIENTACAO_ORIENTACOES-CONSELHEIROS-SAUDE-2-EDICAO_DATA-A-CONFIRMAR_PUB.pdf', 'ORIENTACAO_ORIENTACOES-CONSELHEIROS-SAUDE-2-EDICAO_DATA-A-CONFIRMAR_PUB.pdf', 'Orientacoes_conselheiros_saude_2_edicao', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, 'orientacoes-2', 'secondary_copy'),
  ('19_8qAMPMmhpnUSlwLa9GULWNKyIWL-XE', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/REGIMENTO INTERNO Conselho Municipal de Saúde - 11-02-2016 (1).pdf', 'REGIMENTO INTERNO Conselho Municipal de Saúde - 11-02-2016 (1).pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/REGIMENTO_REGIMENTO-INTERNO-CONSELHO-MUNICIPAL-DE-SAUDE-11-02-2016-1_11-02-2016_PUB.pdf', 'REGIMENTO_REGIMENTO-INTERNO-CONSELHO-MUNICIPAL-DE-SAUDE-11-02-2016-1_11-02-2016_PUB.pdf', 'REGIMENTO INTERNO Conselho Municipal de Saúde - 11-02-2016 (1)', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1YMTWi5dKLdbLA2oGj1Komd6Xg95PiiJS', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/Regimento interno dos Conselhos locais da saúde.pdf', 'Regimento interno dos Conselhos locais da saúde.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/REGIMENTO_REGIMENTO-INTERNO-DOS-CONSELHOS-LOCAIS-DA-SAUDE_DATA-A-CONFIRMAR_PUB.pdf', 'REGIMENTO_REGIMENTO-INTERNO-DOS-CONSELHOS-LOCAIS-DA-SAUDE_DATA-A-CONFIRMAR_PUB.pdf', 'Regimento interno dos Conselhos locais da saúde', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1cb6p-L0qismLlTYQonsQ0ywFNkczwD9O', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/SJvLXSHZRMjqpYJ7QFrrccP.pdf', 'SJvLXSHZRMjqpYJ7QFrrccP.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/NORMA_SJVLXSHZRMJQPYJ7QFRRCCP_DATA-A-CONFIRMAR_PUB.pdf', 'NORMA_SJVLXSHZRMJQPYJ7QFRRCCP_DATA-A-CONFIRMAR_PUB.pdf', 'SJvLXSHZRMjqpYJ7QFrrccP', 'Origem a confirmar na revisão da Diretoria', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1b09RH7gnryxlpgpozpw-xuAF6CWsrPpW', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/TCE_PR_ Orientações_cms.pdf', 'TCE_PR_ Orientações_cms.pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/ORIENTACAO_TCE-PR-ORIENTACOES-CMS_DATA-A-CONFIRMAR_PUB.pdf', 'ORIENTACAO_TCE-PR-ORIENTACOES-CMS_DATA-A-CONFIRMAR_PUB.pdf', 'TCE_PR_ Orientações_cms', 'Tribunal de Contas do Estado', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable'),
  ('1v1KWsKH_Z3nl-tOCs-BQmjPACjIMT_GH', 'CMS Chapada dos Guimarães – Documentos Oficiais/16_Leis e Decretos Municipais/TCU_Orientacoes_para_conselheiros_de_saude_V2_WEB_2_compressed_a9dcb8bb35 (1).pdf', 'TCU_Orientacoes_para_conselheiros_de_saude_V2_WEB_2_compressed_a9dcb8bb35 (1).pdf', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/ORIENTACAO_TCU-ORIENTACOES-PARA-CONSELHEIROS-DE-SAUDE-V2-WEB-2-COMPRESSED-A9DCB8BB35-1_DATA-A-CONFIRMAR_PUB.pdf', 'ORIENTACAO_TCU-ORIENTACOES-PARA-CONSELHEIROS-DE-SAUDE-V2-WEB-2-COMPRESSED-A9DCB8BB35-1_DATA-A-CONFIRMAR_PUB.pdf', 'TCU_Orientacoes_para_conselheiros_de_saude_V2_WEB_2_compressed_a9dcb8bb35 (1)', 'Tribunal de Contas da União', 'public', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, 'tcu-orientacoes', 'secondary_copy'),
  ('1Q4J9mjAS0yMmNnZ0Zx4RyOIF8wnOTWlbdGZi7SD0w78', 'CMS Chapada dos Guimarães – Documentos Oficiais/17_Comunicados/Membros do CMS', 'Membros do CMS', 'Governança e Cadastro Institucional', '13', '13_Governança e Cadastros', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/13_Governança e Cadastros/2026/CADASTRO-MEMBROS_MEMBROS-DO-CMS_DATA-A-CONFIRMAR_RESTRITO', 'CADASTRO-MEMBROS_MEMBROS-DO-CMS_DATA-A-CONFIRMAR_RESTRITO', 'Composição, contatos e perfil digital dos membros do CMS', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'restricted', 'O conteúdo e o nome indicam a classe 13_Governança e Cadastros; o local atual não corresponde à destinação prevista na Política.', 'Mandato vigente e prazo legal aplicável', 'Arquivar composição histórica; eliminar dados operacionais obsoletos mediante termo', true, NULL, 'not_applicable'),
  ('1QXg4hfH6UtHGzfleWg-057FXHFE61Vyg', 'CMS Chapada dos Guimarães – Documentos Oficiais/17_Comunicados/Oficio 424-2026 resolução Municipal.doc', 'Oficio 424-2026 resolução Municipal.doc', 'Documento Recebido', '10', '10_Documentos Recebidos', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/10_Documentos Recebidos/2026/RECEBIDO_OFICIO-424-2026-RESOLUCAO-MUNICIPAL_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.doc', 'RECEBIDO_OFICIO-424-2026-RESOLUCAO-MUNICIPAL_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.doc', 'Oficio 424-2026 resolução Municipal', 'Origem a confirmar na revisão da Diretoria', 'internal', 'O conteúdo e o nome indicam a classe 10_Documentos Recebidos; o local atual não corresponde à destinação prevista na Política.', '2 anos correntes + 3 anos intermediários', 'Eliminar, salvo se vinculado a deliberação ou processo permanente', false, NULL, 'not_applicable'),
  ('1LFU0WTbhwhUenGlTFqe8IbKzSUIg0F9r', 'CMS Chapada dos Guimarães – Documentos Oficiais/17_Comunicados/SESOFI202619866A CIRBC 18.06.2026 ALTERAÃ_Ã_O.pdf', 'SESOFI202619866A CIRBC 18.06.2026 ALTERAÃ_Ã_O.pdf', 'Documento Recebido', '10', '10_Documentos Recebidos', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/10_Documentos Recebidos/2026/RECEBIDO_SESOFI202619866A-CIRBC-18-06-2026-ALTERAA-A-O_18-06-2026_VERSAO-A-CONFIRMAR.pdf', 'RECEBIDO_SESOFI202619866A-CIRBC-18-06-2026-ALTERAA-A-O_18-06-2026_VERSAO-A-CONFIRMAR.pdf', 'SESOFI202619866A CIRBC 18.06.2026 ALTERAÃ_Ã_O', 'Origem a confirmar na revisão da Diretoria', 'internal', 'O conteúdo e o nome indicam a classe 10_Documentos Recebidos; o local atual não corresponde à destinação prevista na Política.', '2 anos correntes + 3 anos intermediários', 'Eliminar, salvo se vinculado a deliberação ou processo permanente', false, NULL, 'not_applicable'),
  ('1YFiaBDewGL3UpFDtsxdVdit0R_8b_eVa', 'CMS Chapada dos Guimarães – Documentos Oficiais/18_Pautas /pauta dia 03-06-2026.docx', 'pauta dia 03-06-2026.docx', 'Convocação ou Pauta', '02', '02_Convocações', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/02_Convocações/2026/PAUTA_PAUTA-DIA-03-06-2026_03-06-2026_VERSAO-A-CONFIRMAR.docx', 'PAUTA_PAUTA-DIA-03-06-2026_03-06-2026_VERSAO-A-CONFIRMAR.docx', 'pauta dia 03-06-2026', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'O conteúdo e o nome indicam a classe 02_Convocações; o local atual não corresponde à destinação prevista na Política.', '1 ano', 'Eliminar após cobertura pela ata e termo', false, NULL, 'not_applicable'),
  ('146XNTFDV9QJau5v29y1OWpQH5402ExN3', 'CMS Chapada dos Guimarães – Documentos Oficiais/18_Pautas /pauta do dia 15-04-2026.docx', 'pauta do dia 15-04-2026.docx', 'Convocação ou Pauta', '02', '02_Convocações', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/02_Convocações/2026/PAUTA_PAUTA-DO-DIA-15-04-2026_15-04-2026_VERSAO-A-CONFIRMAR.docx', 'PAUTA_PAUTA-DO-DIA-15-04-2026_15-04-2026_VERSAO-A-CONFIRMAR.docx', 'pauta do dia 15-04-2026', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'O conteúdo e o nome indicam a classe 02_Convocações; o local atual não corresponde à destinação prevista na Política.', '1 ano', 'Eliminar após cobertura pela ata e termo', false, NULL, 'not_applicable'),
  ('1nXPhmw986BT0Nct4IFLVigIJIkqQTgVm3LM_5rGQ9co', 'CMS Chapada dos Guimarães – Documentos Oficiais/Documentos Oficiais 2026', 'Documentos Oficiais 2026', 'Governança e Cadastro Institucional', '13', '13_Governança e Cadastros', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/13_Governança e Cadastros/2026/GOVERNANCA_DOCUMENTOS-OFICIAIS-2026_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR', 'GOVERNANCA_DOCUMENTOS-OFICIAIS-2026_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR', 'Índice da estrutura documental de 2026', 'Conselho Municipal de Saúde de Chapada dos Guimarães', 'internal', 'O conteúdo e o nome indicam a classe 13_Governança e Cadastros; o local atual não corresponde à destinação prevista na Política.', 'Mandato vigente e prazo legal aplicável', 'Arquivar composição histórica; eliminar dados operacionais obsoletos mediante termo', true, NULL, 'not_applicable'),
  ('1LJiZZ4FMhebez9DwSaJuIBlKAueGbea6', 'CMS Chapada dos Guimarães – Documentos Oficiais/Gravação_9º conferencia.m4a', 'Gravação_9º conferencia.m4a', 'Documento de Conferência', '12', '12_Conferências', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/12_Conferências/2026/CONFERENCIA_GRAVACAO-9-CONFERENCIA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.m4a', 'CONFERENCIA_GRAVACAO-9-CONFERENCIA_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.m4a', 'Gravação_9º conferencia', 'Comissão Organizadora da Conferência / CMS', 'internal', 'O conteúdo e o nome indicam a classe 12_Conferências; o local atual não corresponde à destinação prevista na Política.', 'Até a conferência seguinte', 'Relatório final e atos essenciais em guarda permanente', false, NULL, 'not_applicable'),
  ('11PEcAoqx7hSgEY4uNXMcclsRCgy7iMVa', 'CMS Chapada dos Guimarães – Documentos Oficiais/Política de Gestão Documental do CMS.docx', 'Política de Gestão Documental do CMS.docx', 'Legislação, Norma ou Referência Técnica', '09', '09_Legislação e Normas', 'CMS_GESTAO_DOCUMENTAL/01_Acervo_Interno_CMS/09_Legislação e Normas/NORMA_POLITICA-DE-GESTAO-DOCUMENTAL-DO-CMS_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'NORMA_POLITICA-DE-GESTAO-DOCUMENTAL-DO-CMS_DATA-A-CONFIRMAR_VERSAO-A-CONFIRMAR.docx', 'Política de Gestão Documental do CMS', 'Origem a confirmar na revisão da Diretoria', 'internal', 'O conteúdo e o nome indicam a classe 09_Legislação e Normas; o local atual não corresponde à destinação prevista na Política.', 'Enquanto vigente ou útil à fundamentação', 'Preservar normas estruturantes; revisar referências obsoletas', false, NULL, 'not_applicable')
)
INSERT INTO document_classification_proposals (
  batch_id, document_id, drive_file_id, current_path, original_filename,
  classification_type, folder_code, recommended_folder, recommended_path,
  proposed_filename, subject, origin, recommended_visibility,
  classification_rationale, retention_rule, final_destination,
  requires_policy_amendment, duplicate_group, duplicate_disposition,
  status, movement_status
)
SELECT '00000000-0000-4000-8000-000000000003', document.id,
       source.drive_file_id, source.current_path, source.original_filename,
       source.classification_type, source.folder_code, source.recommended_folder,
       source.recommended_path, source.proposed_filename, source.subject,
       source.origin, source.recommended_visibility::visibility_scope,
       source.classification_rationale, source.retention_rule,
       source.final_destination, source.requires_policy_amendment,
       source.duplicate_group, source.duplicate_disposition,
       'pending_directorate', 'not_authorized'
FROM source JOIN documents document ON document.drive_file_id = source.drive_file_id
ON CONFLICT (batch_id, document_id) DO UPDATE SET
  current_path = EXCLUDED.current_path,
  original_filename = EXCLUDED.original_filename,
  classification_type = EXCLUDED.classification_type,
  folder_code = EXCLUDED.folder_code,
  recommended_folder = EXCLUDED.recommended_folder,
  recommended_path = EXCLUDED.recommended_path,
  proposed_filename = EXCLUDED.proposed_filename,
  subject = EXCLUDED.subject,
  origin = EXCLUDED.origin,
  recommended_visibility = EXCLUDED.recommended_visibility,
  classification_rationale = EXCLUDED.classification_rationale,
  retention_rule = EXCLUDED.retention_rule,
  final_destination = EXCLUDED.final_destination,
  requires_policy_amendment = EXCLUDED.requires_policy_amendment,
  duplicate_group = EXCLUDED.duplicate_group,
  duplicate_disposition = EXCLUDED.duplicate_disposition,
  updated_at = now();

INSERT INTO audit_logs (entity_type, entity_id, action, details, actor_name, actor_role)
SELECT 'classification_plan', batch.id, 'classification_plan_prepared',
       jsonb_build_object(
         'documents', batch.document_count,
         'misplaced', batch.misplaced_count,
         'restricted', batch.restricted_count,
         'requiresPolicyAmendment', batch.requires_policy_amendment_count,
         'duplicateFiles', batch.duplicate_file_count,
         'movementAuthorized', false
       ), 'Análise documental da Etapa 3', 'master'
FROM document_classification_batches batch
WHERE batch.id = '00000000-0000-4000-8000-000000000003'
  AND NOT EXISTS (
    SELECT 1 FROM audit_logs audit
    WHERE audit.entity_type = 'classification_plan'
      AND audit.entity_id = batch.id
      AND audit.action = 'classification_plan_prepared'
  );

COMMIT;

