import Link from "next/link";
import { notFound } from "next/navigation";
import { listKosAnalysesForProtocol } from "../../../../lib/kos-analysis";
import { getReceivedProtocol, listLinkableDocuments, listProtocolUsers, nextProtocolStatuses, protocolStatusLabels } from "../../../../lib/protocols";
import { requireAdmin } from "../../../../lib/session";
import { hasRole, roleLabel } from "../../../../lib/users";

export const dynamic = "force-dynamic";
export const metadata = { title: "Acompanhamento de protocolo | CMS", robots: { index: false, follow: false } };

const priorityLabel = { baixa: "Baixa", normal: "Normal", alta: "Alta", urgente: "Urgente" };
const visibilityLabel = { public: "Público", internal: "Interno", restricted: "Restrito" };
const originLabel = { presencial: "Presencial", email: "E-mail", correios: "Correios", sistema: "Sistema eletrônico", outro: "Outro" };
const relationLabel = { resposta: "Resposta", parecer: "Parecer", oficio: "Ofício", deliberacao: "Deliberação", outro: "Outro" };

function formatDate(value: string | null) {
  return value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "America/Cuiaba" }).format(new Date(`${value}T12:00:00`)) : "Não informado";
}

export default async function ProtocolDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string; saved?: string; error?: string; kosError?: string }> }) {
  const session = await requireAdmin();
  const [{ id }, state] = await Promise.all([params, searchParams]);
  if (!/^[0-9a-f-]{36}$/i.test(id)) notFound();
  const result = await getReceivedProtocol(id, session);
  if (!result) notFound();
  const { protocol, events, links } = result;
  const mayManage = hasRole(session, "gestao");
  const maySetPublic = hasRole(session, "diretoria_cms");
  const [users, documents, analyses] = await Promise.all([
    mayManage ? listProtocolUsers() : Promise.resolve([]),
    mayManage ? listLinkableDocuments(protocol.documentId) : Promise.resolve([]),
    listKosAnalysesForProtocol(protocol.id, session),
  ]);
  const nextStatuses = nextProtocolStatuses(protocol.status, session);
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Cuiaba" }).format(new Date());
  const overdue = protocol.responseDueDate && protocol.responseDueDate < today && protocol.status !== "arquivado";

  return <main className="min-h-screen bg-[#f2f7fb] text-[#40566a]">
    <header className="border-b border-[#cbdce8] bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 px-6 py-4"><Link href="/admin/protocolos" className="font-bold text-[#17375e]">← Documentos recebidos</Link><div className="flex flex-wrap gap-4"><Link href={`/admin/protocolos/${id}/recibo`} className="font-bold text-[#315f7d]">Ver recibo</Link><a href={`/api/admin/protocolos/${id}/arquivo`} className="font-bold text-[#087f5b]">Abrir documento</a></div></div></header>
    <section className="mx-auto max-w-7xl px-6 py-12">
      <p className="text-sm font-bold uppercase tracking-[.16em] text-[#28738c]">{protocol.protocolNumber}</p><h1 className="mt-3 max-w-4xl text-4xl font-bold text-[#17375e]">{protocol.subject}</h1>
      <div className="mt-5 flex flex-wrap gap-3"><span className="rounded-full bg-sky-100 px-4 py-2 text-sm font-bold text-sky-900">{protocolStatusLabels[protocol.status]}</span><span className="rounded-full bg-amber-100 px-4 py-2 text-sm font-bold text-amber-950">Prioridade {priorityLabel[protocol.priority].toLowerCase()}</span><span className={`rounded-full px-4 py-2 text-sm font-bold ${overdue ? "bg-red-100 text-red-900" : "bg-emerald-100 text-emerald-900"}`}>{protocol.responseDueDate ? `${overdue ? "Prazo vencido" : "Prazo"}: ${formatDate(protocol.responseDueDate)}` : "Sem prazo definido"}</span></div>
      {state.created ? <p role="status" className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 font-bold text-emerald-900">Protocolo e recibo gerados com sucesso.</p> : null}{state.saved ? <p role="status" className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 font-bold text-emerald-900">Tramitação registrada no histórico.</p> : null}{state.error ? <p role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-900">Não foi possível registrar a tramitação. Verifique a transição, os campos e seu nível de acesso.</p> : null}
      {state.kosError ? <p role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-900">A análise KOS não foi concluída. Código: {state.kosError}. Consulte os limites no painel do KOS ou verifique se o PDF possui texto pesquisável.</p> : null}

      <div className="mt-8 grid gap-5 lg:grid-cols-3">
        <article className="rounded-2xl border border-[#d5e3ec] bg-white p-6"><h2 className="text-xl font-bold text-[#17375e]">Recebimento</h2><dl className="mt-5 grid gap-3 text-sm"><div><dt className="font-bold text-[#60758a]">Data e canal</dt><dd>{formatDate(protocol.receivedAt)} · {originLabel[protocol.originChannel]}</dd></div><div><dt className="font-bold text-[#60758a]">Remetente</dt><dd>{protocol.senderName}</dd></div><div><dt className="font-bold text-[#60758a]">Organização</dt><dd>{protocol.senderOrganization ?? "Não informada"}</dd></div><div><dt className="font-bold text-[#60758a]">Contato</dt><dd>{protocol.senderEmail ?? "E-mail não informado"}<br />{protocol.senderPhone ?? "Telefone não informado"}</dd></div></dl></article>
        <article className="rounded-2xl border border-[#d5e3ec] bg-white p-6"><h2 className="text-xl font-bold text-[#17375e]">Controle</h2><dl className="mt-5 grid gap-3 text-sm"><div><dt className="font-bold text-[#60758a]">Responsável</dt><dd>{protocol.responsibleName ?? "A definir"}</dd></div><div><dt className="font-bold text-[#60758a]">Área ou comissão</dt><dd>{protocol.assignedArea ?? "A definir"}</dd></div><div><dt className="font-bold text-[#60758a]">Acesso</dt><dd>{visibilityLabel[protocol.visibility]}</dd></div><div><dt className="font-bold text-[#60758a]">Criado por</dt><dd>{protocol.createdByName}</dd></div></dl></article>
        <article className="rounded-2xl border border-[#d5e3ec] bg-white p-6"><h2 className="text-xl font-bold text-[#17375e]">Documento</h2><p className="mt-5 text-sm"><strong>Arquivo:</strong> {protocol.originalFilename ?? "Nome não registrado"}</p><p className="mt-2 text-sm"><strong>Resumo:</strong> {protocol.summary ?? "Sem resumo"}</p><div className="mt-5 grid gap-2"><a href={`/api/admin/protocolos/${id}/arquivo`} className="font-bold text-[#087f5b] hover:underline">Abrir arquivo recebido →</a><Link href={`/admin/documentos/${protocol.documentId}/historico`} className="font-bold text-[#315f7d] hover:underline">Histórico documental →</Link></div></article>
      </div>

      <section className="mt-10 rounded-2xl border border-[#d5e3ec] bg-white p-6"><h2 className="text-2xl font-bold text-[#17375e]">Fluxo institucional</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-7">{Object.entries(protocolStatusLabels).map(([status, label], index) => { const currentIndex = Object.keys(protocolStatusLabels).indexOf(protocol.status); const active = index <= currentIndex; return <div key={status} className={`rounded-xl border p-3 text-sm font-bold ${active ? "border-[#76a9bd] bg-[#dcecf5] text-[#17375e]" : "border-[#d5e3ec] bg-white text-[#60758a]"}`}><span className="block text-xs">{String(index + 1).padStart(2, "0")}</span>{label}</div>; })}</div><p className="mt-4 text-xs font-semibold">A etapa “Análise do KOS” registra o encaminhamento para análise automatizada. O conteúdo só poderá avançar após validação humana.</p></section>

      <section className="mt-10 rounded-2xl border-2 border-[#76a9bd] bg-white p-6">
        <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-[#28738c]">Apoio técnico</p><h2 className="mt-2 text-2xl font-bold text-[#17375e]">Análise documental do KOS</h2><p className="mt-3 max-w-3xl leading-7">O PDF será lido e anonimizado no servidor. A análise não publica, movimenta ou decide nada e precisará de validação humana.</p></div><Link href="/admin/kos" className="font-bold text-[#087f5b]">Ver limites e histórico →</Link></div>
        {protocol.status === "triagem" || protocol.status === "analise_kos" || protocol.status === "validacao_humana" ? <form method="post" action={`/api/admin/protocolos/${id}/analise`} className="mt-5"><button className="rounded-xl bg-[#315f7d] px-6 py-3 font-bold text-white">{analyses.length ? "Consultar ou repetir análise permitida" : "Solicitar análise do KOS"}</button></form> : <p className="mt-5 rounded-xl bg-[#f2f7fb] p-4 font-semibold">A análise ficará disponível depois que a Gestão concluir a triagem do protocolo.</p>}
        <div className="mt-6 grid gap-3">{analyses.map((analysis) => <article key={analysis.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#f2f7fb] p-4"><div><strong className="text-[#234c68]">{analysis.status === "pending_review" ? "Aguardando validação" : analysis.status === "approved" ? "Aprovada" : analysis.status === "corrected" ? "Corrigida" : analysis.status === "rejected" ? "Rejeitada" : analysis.status === "failed" ? "Falha" : analysis.status === "quota_blocked" ? "Bloqueada por limite" : "Processando"}</strong><p className="mt-1 text-xs">Solicitada por {analysis.requestedByName} · {new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Cuiaba" }).format(new Date(analysis.createdAt))}</p></div><Link href={`/admin/kos/${analysis.id}`} className="font-bold text-[#087f5b]">Abrir resultado →</Link></article>)}</div>
      </section>

      {mayManage ? <form method="post" action={`/api/admin/protocolos/${id}`} className="mt-10 grid gap-6 rounded-2xl border border-[#d5e3ec] bg-white p-6"><h2 className="text-2xl font-bold text-[#17375e]">Registrar triagem ou encaminhamento</h2>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3"><label className="grid gap-2 font-semibold text-[#315f7d]"><span>Nova situação</span><select name="status" className="input"><option value={protocol.status}>Manter: {protocolStatusLabels[protocol.status]}</option>{nextStatuses.map((status) => <option key={status} value={status}>Avançar para: {protocolStatusLabels[status]}</option>)}</select></label><label className="grid gap-2 font-semibold text-[#315f7d]"><span>Prioridade</span><select name="priority" defaultValue={protocol.priority} className="input">{Object.entries(priorityLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-2 font-semibold text-[#315f7d]"><span>Prazo de resposta</span><input name="responseDueDate" type="date" defaultValue={protocol.responseDueDate ?? ""} className="input" /></label><label className="grid gap-2 font-semibold text-[#315f7d]"><span>Nível de acesso</span><select name="visibility" defaultValue={protocol.visibility === "public" && !maySetPublic ? "internal" : protocol.visibility} className="input">{maySetPublic ? <option value="public">Público</option> : null}<option value="internal">Interno</option><option value="restricted">Restrito</option></select></label><label className="grid gap-2 font-semibold text-[#315f7d]"><span>Área, comissão ou destino</span><input name="assignedArea" maxLength={250} defaultValue={protocol.assignedArea ?? ""} className="input" /></label><label className="grid gap-2 font-semibold text-[#315f7d]"><span>Responsável</span><select name="responsibleUserId" defaultValue={protocol.responsibleUserId ?? ""} className="input"><option value="">A definir</option>{users.map((user) => <option key={user.id} value={user.id}>{user.fullName} · {roleLabel(user.role as Parameters<typeof roleLabel>[0])}</option>)}</select></label></div>
        <label className="grid gap-2 font-semibold text-[#315f7d]"><span>Registro da ação ou justificativa</span><textarea name="notes" required minLength={3} maxLength={3000} rows={4} className="input" placeholder="Descreva a triagem, o encaminhamento ou a decisão humana." /></label>
        <fieldset className="grid gap-5 border-t border-[#d5e3ec] pt-6 md:grid-cols-3"><legend className="mb-4 text-lg font-bold text-[#17375e]">Vincular resposta, parecer, ofício ou deliberação (opcional)</legend><label className="grid gap-2 font-semibold text-[#315f7d] md:col-span-2"><span>Documento existente</span><select name="linkedDocumentId" className="input"><option value="">Não vincular agora</option>{documents.map((document) => <option key={document.id} value={document.id}>{document.documentNumber ? `${document.documentNumber} · ` : ""}{document.title}</option>)}</select></label><label className="grid gap-2 font-semibold text-[#315f7d]"><span>Relação</span><select name="linkRelation" className="input"><option value="">Selecione</option>{Object.entries(relationLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-2 font-semibold text-[#315f7d] md:col-span-3"><span>Observação do vínculo</span><input name="linkNotes" maxLength={1000} className="input" /></label></fieldset>
        <button className="w-fit rounded-xl bg-[#315f7d] px-6 py-3 font-bold text-white hover:bg-[#234c68]">Registrar no histórico</button></form> : null}

      <div className="mt-10 grid gap-8 lg:grid-cols-2"><section><h2 className="text-2xl font-bold text-[#1f5872]">Histórico completo</h2><div className="mt-5 grid gap-4">{events.map((event) => <article key={event.id} className="rounded-2xl border border-[#d5e3ec] bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><strong className="text-[#234c68]">{protocolStatusLabels[event.newStatus]}</strong><time className="text-xs font-semibold">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Cuiaba" }).format(new Date(event.createdAt))}</time></div><p className="mt-2 text-sm">{event.notes ?? "Ação registrada sem observação."}</p><p className="mt-3 text-xs">Por <strong>{event.actorName}</strong> · {event.assignedArea ?? "sem área indicada"} · {event.responsibleName ?? "sem responsável indicado"}</p></article>)}</div></section><section><h2 className="text-2xl font-bold text-[#1f5872]">Documentos vinculados</h2><div className="mt-5 grid gap-4">{links.length ? links.map((link) => <article key={link.id} className="rounded-2xl border border-[#d5e3ec] bg-white p-5"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-900">{relationLabel[link.relation]}</span><h3 className="mt-3 font-bold text-[#234c68]">{link.documentTitle}</h3><p className="mt-2 text-sm">{link.notes ?? "Sem observação adicional."}</p><Link href={`/admin/documentos/${link.documentId}/historico`} className="mt-3 inline-flex font-bold text-[#087f5b]">Consultar documento →</Link></article>) : <p className="rounded-2xl border border-[#d5e3ec] bg-white p-6">Nenhum documento de resposta ou deliberação foi vinculado.</p>}</div></section></div>
    </section>
  </main>;
}
