import Image from "next/image";
import Link from "next/link";

const actions = ["Consultar documentos", "Comparar documentos", "Conferência × PMS × PAS", "Analisar pauta", "Consultar legislação", "Criar minuta"];

export default function Home() {
  return <main className="min-h-screen bg-[#07111f] text-white">
    <section className="relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,rgba(245,158,11,.16),transparent_26%),radial-gradient(circle_at_10%_80%,rgba(16,185,129,.12),transparent_28%)]" /><div className="relative mx-auto max-w-4xl px-6 py-20 text-center md:py-28"><p className="text-sm font-bold uppercase tracking-[.35em] text-amber-400">Central de consulta</p><h1 className="mt-5 text-5xl font-bold leading-tight md:text-6xl">Sabedoria antiga,<span className="text-amber-400"> gestão moderna.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300">Uma base técnico-institucional para consultar propostas, PMS e PAS com referências documentais.</p><Link href="/consulta" className="mt-9 inline-flex rounded-xl bg-amber-400 px-6 py-3 font-bold text-slate-950 hover:bg-amber-300">Pergunte ao KOS</Link></div></section>
    <section className="mx-auto max-w-6xl px-6 pb-20"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{actions.map((action, index) => <Link href="/consulta" key={action} className="group rounded-2xl border border-slate-800 bg-slate-900/70 p-6 transition hover:-translate-y-1 hover:border-amber-400"><span className="text-sm font-bold text-amber-400">0{index + 1}</span><p className="mt-8 text-lg font-bold">{action}</p><span className="mt-4 inline-flex text-sm font-semibold text-slate-400 group-hover:text-amber-300">Consultar →</span></Link>)}</div><section className="mt-12 rounded-3xl border border-slate-800 bg-slate-900 p-6 md:p-8"><h2 className="text-xl font-bold">Consulta com evidências</h2><p className="mt-3 max-w-3xl leading-7 text-slate-300">Pesquise palavras como “UBS”, “medicamentos”, “laboratório” ou “Melhor em Casa” para ver a proposta e o que foi registrado no PMS e na PAS.</p><Link href="/consulta" className="mt-5 inline-flex rounded-xl border border-amber-400 px-5 py-3 font-bold text-amber-300 hover:bg-amber-400 hover:text-slate-950">Abrir consulta documental</Link></section></section>
    <footer className="border-t border-slate-800 bg-slate-950"><div className="mx-auto flex max-w-6xl flex-col gap-6 px-6 py-8 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><div className="grid shrink-0 gap-2"><Image src="/cms-logo.jpeg" alt="Logotipo do Conselho Municipal de Saúde" width={56} height={56} className="rounded-xl bg-[#fffbed] p-1" /><span className="block h-10 w-[145px] overflow-hidden rounded-lg bg-white"><Image src="/secretaria-saude-colorida.png" alt="Secretaria Municipal de Saúde de Chapada dos Guimarães" width={145} height={52} className="h-full w-full scale-[1.18] object-cover" /></span></div><p className="text-sm leading-6 text-slate-300">KOS · Conselho Municipal de Saúde<br />Chapada dos Guimarães – MT</p></div><div className="text-sm text-slate-400"><a href="tel:+5565992326757" className="hover:text-white">(65) 99232-6757</a><span className="mx-2">•</span><a href="https://cms.chapada.ia.br" className="hover:text-white">Portal institucional</a></div></div></footer>
  </main>;
}
